export const PERM_LIST_REQUEST = 'PERM_LIST_REQUEST'
export const PERM_LIST_SUCCESS = ' PERM_LIST_SUCCESS'
export const PERM_LIST_FAIL = 'PERM_LIST_FAIL'

export const PERM_CREATE_REQUEST = 'PERM_CREATE_REQUEST'
export const PERM_CREATE_SUCCESS = ' PERM_CREATE_SUCCESS'
export const PERM_CREATE_FAIL = 'PERM_CREATE_FAIL'
